### ISSUE TITLE
dasherize should allow to omit leading dash

### ISSUE THREAD

**Issue by rbu** [esamattis/underscore.string#167]
When leading dashes are not allowed or nor desired in a string to be dasherized, it would be helpful to simply remove them. Maybe like this:

```
_('Css-Class').dasherize();
"-css-class"
_('Css-Class').dasherize(true);
"css-class"
```

**Comment by bolora** [comment]
We use this workaround using &lowbar;.underscored which works correctly.
_.dasherize(&lowbar;.underscored( 'FooBar' )) returns 'foo-bar'
