### ISSUE TITLE
Pluralize function

### ISSUE THREAD

**Issue by machineghost** [esamattis/underscore.string#176]
This request strikes me as pretty obvious, but just to be clear I'm requesting a method like:

```
pluralize("apple") == "apples";
pluralize("puppy") == "puppies";
```

If all this function did was just:

```
 return _(word).endsWith('y') ?
          word.substring(word.length - 1) + 'ies' :
          word + 's';
```

it would still be very useful, but if it could handle some of the common edge cases in the English language that'd be even better.

Oh, and I saw that there was already a ticket for this, but it was closed without explanation, so I figured the appropriate thing to do was start a new ticket.  If this is incorrect I'll be more than happy to comment on that ticket instead (or open a pull request, or whatever else makes the devs lives easier).

**Comment by DavidMikeSimon** [comment]
:+1: on a simple version like the one proposed by machineghost. One small hangup, however: non-integer quantities and zero also need to be pluralized (e.g. "I have zero apples" or "I have zero-point-five gigabytes of RAM"), so the right check here is `number == 1`, not `number > 1`.

**Comment by DouglasLivingstone** [comment]
Internationalisation of pluralisation is hard, here is a list of pluralisation rules in different languages: http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html

All the languages with nplurals > 2 would not work with a three argument version of _.pluralize(n, a, b), so this is indeed best left to dedicated pluralisation libraries.

**Comment by machineghost** [comment]
>All the languages with nplurals > 2 would not work with a three argument version

I'd compare it to Underscore String's `count` method.  Languages like Chinese or Japanese don't rely on spaces for word separation, so for `count` to work properly on those languages the library would need special (non-trivial, outside the scope of the library) Chinese/Japanese logic added.

Yet `count` was included, presumably because it's still useful for anyone whose language *does* have spaces.  Same deal here: right now English-speaking Underscore String users have three options:

1. use a whole pluralization library
2. use lots of ternaries
3. avoid pluralization entirely

A basic `pluralize` method will never beat out #1, but it could be a very welcome alternative to #2 and #3.  I'd argue that's a good thing, and again that we should avoid sacrificing the good for the great.

Plus, Underscore String doesn't even *mention* the world "international" anywhere on the site, which suggests to me that internationalization isn't a dominant concern.
