### ISSUE TITLE
prune() fails with strings containing no white space

### ISSUE THREAD

**Issue by rygine** [esamattis/underscore.string#214]
_.prune('asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf', 10)

results in "..."

**Comment by imajus** [comment]
That doesn't look like a correct result for me. The reason I choose third-party libraries like underscore.string is _convenience_. I don't want to spend time reinventing wheels over and over again. I'm pretty sure anyone wants utility libraries like this to work out of box and cover most common cases.
So the most common case I use `prune` for excerpts of is user generated content. I can't forbid them to enter 100 symbols in a row without whitespaces. And still I'd like to use clear function to make excerpts.
Of course, now when I know that `prune` doesn't behave correctly for such strings I'll make my own workaround. Probably using combination of `truncate` and `prune`. But I believe underscore.string should provide convenient and clear method out of box for such common case. 
Maybe it would be a good idea for `prune` to not just fail silently when result length is `0` but to fallback to `truncate`?
