### ISSUE TITLE
_.dasherize( 'Foo' ) returning '-foo'

### ISSUE THREAD

**Issue by AshHeskes** [esamattis/underscore.string#311]
Possible Fix:

```
function dasherize ( string ) {

    return string. replace ( /([^])([A-Z]+)([^$])/g, '$1-$2$3' ). toLowerCase();
}
```

**Comment by bolora** [comment]
This makes no sense that it was closed without a resolution.  In no case does _.dasherize( 'Foo' ) returning '-foo' make any sense.

For now we use a workaround using _.underscored works correctly.
_.dasherize(_.underscored( 'FooBar' )) returns 'foo-bar'

**Comment by stoeffel** [comment]
This is by design. see https://epeli.github.io/underscore.string/#dasherize-string-gt-string

You can also use decapitalize if you don't want this.
