### ISSUE TITLE
Jumble function?

### ISSUE THREAD

**Issue by asad-awadia** [esamattis/underscore.string#441]
Looking to contribute to the repo - Would a jumble function be considered useful?

`jumble("abcd") => "bdac"`

**Comment by stoeffel** [comment]
Hi @asad-awadia. 
I actually don't see a need for a `jumble` function at the moment. Do you have a use-case for it?
If you are looking to contribute to `underscore.string` the [issues](https://github.com/epeli/underscore.string/issues) are a good starting point.

Looking forward to see a contribution from you.
Thanks
