### ISSUE TITLE
Vulnerable Regular Expression

### ISSUE THREAD

**Issue by cristianstaicu** [esamattis/underscore.string#510]
The following regular expression used in unescapeHTML is vulnerable to ReDoS:
```js
/\&([^;]+);/g
```
The slowdown is moderately low: for 50.000 characters around 2 seconds matching time. However, I would still suggest one of the following: 
- remove the regex,
- anchor the regex,
- limit the number of characters that can be matched by the repetition,
- limit the input size.

If needed, I can provide an actual example showing the slowdown.

**Comment by simonstewart-bridgement** [comment]
Any movement on this?

**Comment by epeli** [comment]
Maybe? https://github.com/epeli/underscore.string/pull/517

**Comment by magesh0819** [comment]
Though the regex in question has been updated in unescapeHTML.js it is present in underscore.string.js and underscore.string.min.js. Hence the 3.3.5 version in npm registry is still vulnerable to the Regular expression Denial of Service (ReDoS) attack.

**Comment by PenguinOfWar** [comment]
This appears to still be an issue. NPM audit is showing a vulnerability for this package even when fuklly up to date with the latest version.

Am I missing something?

**Comment by esamattis** [comment]
We tried to fix this issue sometime ago. Really not sure what should be done more to solve it. PRs are very much welcome.

I'll re-open this issue to get more eyes on it.

**Comment by PenguinOfWar** [comment]
> We tried to fix this issue sometime ago. Really not sure what should be done more to solve it. PRs are very much welcome.
> 
> I'll re-open this issue to get more eyes on it.

Thanks @esamattis.

I have created a pull request for this issue: #525 

Appreciate if you can check and, if happy, merge and redeploy to npm to resolve this vulnerability.

**Comment by PenguinOfWar** [comment]
Any update on this?

**Comment by DarkAbstergo** [comment]
Any update on this?

**Comment by carneam** [comment]
Hi, is there any update on the merge eta to correct the outstanding vulnerability issue?

**Comment by esamattis** [comment]
3.3.6 is out.
